In [77]:
#Delvin Mackenzie
#Json worldbank exercise
#Springboard

import pandas as pd
import json 
from pandas.io.json import json_normalize
from collections import Counter
import numpy as np

#I applied 2 seperate mothods to import json data for the purpose of practice even though its redundant. 

#loads worldbank json data: worldbank_json
worldbank_json = json.load((open('Downloads/data_wrangling_json/data/world_bank_projects.json')))

#loads worldbank json data into a pandas DataFrame: df
df= pd.read_json('Downloads/data_wrangling_json/data/world_bank_projects.json')

#slices countrycode column from df: country_code
country_code = df.loc[:,['countrycode']]

#creates counter on country_code: country_counter
country_counter = Counter(country_code['countrycode'].tolist())

#prints a list of tuples of the top 10 country codes and number of occurances as a list
print(country_counter.most_common(10))

#takes the json worldbank file and normalizes into a pandas DataFrame: mjtheme_normalized
mjtheme_normalized = json_normalize(worldbank_json,'mjtheme_namecode')

#Creates a counter for the 'name' column in the worldbank DataFrame: theme_counter
theme_counter = Counter(mjtheme_normalized['name'].tolist())

#prints a list of tuples of the top 10 project themes and number of occurances as a list
theme_counter.most_common(10)

[('CN', 19), ('ID', 19), ('VN', 17), ('IN', 16), ('RY', 13), ('MA', 12), ('NP', 12), ('BD', 12), ('MZ', 11), ('3A', 11)]

[('Environment and natural resources management', 223),
 ('Rural development', 202),
 ('Human development', 197),
 ('Public sector governance', 184),
 ('Social protection and risk management', 158),
 ('Financial and private sector development', 130),
 ('', 122),
 ('Social dev/gender/inclusion', 119),
 ('Trade and integration', 72),
 ('Urban development', 47)]

In [78]:
#creates pandas DataFrame from theme_counter to visually display top 10 project themes
theme_df = pd.DataFrame.from_dict(theme_counter, orient='index').reset_index().head(10)
theme_df = theme_df.rename(columns={'index':'theme', 0:'count'})
theme_df = theme_df.sort_values('count', ascending=False)
theme_df

                                          theme  count
6  Environment and natural resources management    223
9                             Rural development    202
0                             Human development    197
5                      Public sector governance    184
3         Social protection and risk management    158
8      Financial and private sector development    130
1                                                  122
7                   Social dev/gender/inclusion    119
4                         Trade and integration     72
2                           Economic management     33

In [79]:

#creates pandas DataFrame from theme_counter to visually display top 10 countries
top_country_df = pd.DataFrame.from_dict(country_counter, orient='index').reset_index().head(10)
top_country_df = top_country_df.rename(columns={'index':'theme', 0:'count'})
top_country_df = top_country_df.sort_values('count', ascending=False)
top_country_df

  theme  count
7    CN     19
6    IN     16
3    RY     13
8    MA     12
5    KE      6
0    ET      4
1    TN      4
4    LS      3
9    SS      3
2    TV      1

In [80]:
#list of project themes 
theme_value_list = ["Economic management","Public sector governance", "Urban development", "Financial and private sector development",
                   "Trade and integration", "Social protection and risk management", "Social dev/gender/inclusion",
                    "Human development", "Urban development", "Rural development", "Environment and natural resources management"]

In [81]:
#iterates over each row of theme to replace empty values with the correct theme
for index, row in mjtheme_normalized.iterrows():
    if row['name'] == '':
       row['name'] = theme_value_list[int(row['code']) - 1]
mjtheme_normalized

     code                                          name
0       8                             Human development
1      11  Environment and natural resources management
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6         Social protection and risk management
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8                             Human development
18     10                             Rural development
19      7                   Social dev/gender/inclusion
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                      Public sector governance
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4      Financial and private sector development
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11  Environment and natural resources management
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5                         Trade and integration
1482    6         Social protection and risk management
1483    8                             Human development
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6         Social protection and risk management
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]